export const caregiversData = [
  {
    id: 1,
    serialno: "0541",
    caregiver: "Nneka Ossai",
    doctor: "Nuhu Ahmadu",
    requestType: "Vaccination",
    role: "Mother",
    email: "email@mail.com",
    phone: "+2347034536782",
    noOfChildren: "2",
    children: [
      {
        name: "Christopher Ossai",
        sex: "Male",
        age: "6 months",
        dob: "22-01-2021",
        weight: "6kg",
        allergies: "None",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "12-04-2021",
      },
      {
        name: "Cynthia Ossai",
        sex: "Female",
        age: "2 years",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "Dust",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
    ],
    nameOfChild: "Ada Okafor",
    complaint: "Cough",
    prescription: "Vitamin B Complex, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "15-12-2021",
    time: "4:00 PM",
    status: "Active",
  },
  {
    id: 2,
    serialno: "0561",
    caregiver: "Maryam Aliyu",
    doctor: "Adedolapo Ajasco",
    requestType: "Vittual Consultation",
    role: "Mother",
    noOfChildren: "1",
    email: "email@yyyymail.com",
    phone: "+2347034536782",
    children: [
      {
        name: "Adams Aliyu",
        sex: "Male",
        age: "6 months",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "None",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
      {
        name: "Fidausi Aliyu",
        sex: "Female",
        age: "2 years",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "Peanut",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "02-02-2021",
      },
    ],
    nameOfChild: "Shayne Ajasco",
    complaint: "Running Temperature",
    prescription: "Chloraphenicol, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "05-02-2021",
    time: "3:00 PM",
    status: "Restricted",
  },
  {
    id: 3,
    serialno: "0581",
    caregiver: "Vince Calistus",
    doctor: "Obinna Okereke",
    requestType: "Vaccination",
    role: "Guardian",
    email: "email@mail.com",
    phone: "+2347034536782",
    noOfChildren: "2",
    children: [
      {
        name: "Kali Calistus",
        sex: "Male",
        age: "6 months",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "Peanut",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
      {
        name: "Vinnie Calistus",
        sex: "Female",
        age: "2 years",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "Peanut",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
    ],
    nameOfChild: "Vinnie Santino",
    complaint: "Dysentry",
    prescription: "Vitamin B Complex, Multivitamin syrup",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "24-03-2021",
    time: "9:00 AM",
    status: "Restricted",
  },
  {
    id: 4,
    serialno: "0941",
    caregiver: "Adekunle Taribo",
    doctor: "Johnny Maguire",
    requestType: "Vittual Consultation",
    role: "Father",
    email: "email@gggmail.com",
    phone: "+2347034536782",
    noOfChildren: "2",
    children: [
      {
        name: "Adekunle Gold",
        sex: "Male",
        age: "3 years",
        dob: "22-03-2021",
        weight: "5kg",
        allergies: "Dust",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-05-2021",
      },
      {
        name: "Simi Adekunle",
        sex: "Female",
        age: "2 years",
        dob: "22-01-2021",
        weight: "10kg",
        allergies: "Peanut",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
    ],
    nameOfChild: "Adekunle Simi",
    complaint: "Cold",
    prescription: "Vitamin B Complex, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "03-05-2021",
    time: "12:00 AM",
    status: "Active",
  },
  {
    id: 5,
    serialno: "0781",
    caregiver: "Lucy Ekanem",
    doctor: "Peter Drury",
    requestType: "Vittual Consultation",
    role: "Mother",
    email: "email@hotmail.com",
    phone: "+2347034536782",
    noOfChildren: "2",
    children: [
      {
        name: "Christopher Ekanem",
        sex: "Male",
        age: "6 months",
        dob: "22-02-2021",
        weight: "5kg",
        allergies: "Peanut, Dust",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-02-2021",
      },
      {
        name: "Karo Ekanem",
        sex: "Female",
        age: "2 years",
        dob: "22-03-2021",
        weight: "10kg",
        allergies: "Dust",
        specialNeeds: "None",
        medCond: "None",
        dateOfReg: "22-05-2021",
      },
    ],
    nameOfChild: "Iniobong Abang",
    complaint: "Fever",
    prescription: "Paracetamol, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "25-04-2021",
    time: "11:00 AM",
    status: "Restricted",
  },
];
