export const bookRequestData = [
  {
    id: 1,
    serialno: "0541",
    caregiver: "Nneka Ossai",
    email: "wemove@hotmail.com",
    phone: "+2347034536782",
    address: "15 Oladipo Diya Avenue V.I, Lagos",
    location: "Home",
    doctor: "Nuhu Ahmadu",
    requestType: "Vaccination",
    role: "Mother",
    noOfChildren: "2",
    nameOfChild: "Ada Okafor",
    dob: "22-01-2021",
    weight: "10kg",
    allergies: "peanut",
    specialNeeds: "",
    medCondition: "",
    sex: "Female",
    age: "1 year",
    complaint: "Cough",
    prescription: "Vitamin B Complex, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "15-12-2021",
    time: "4:00 PM",
    status: "Declined",
  },
  {
    id: 2,
    serialno: "0561",
    caregiver: "Maryam Aliyu",
    email: "email@hotmail.com",
    phone: "+2347034536782",
    address: "15 Oladipo Diya Avenue Ajah, Lagos",
    location: "Home",
    doctor: "Adedolapo Ajasco",
    requestType: "Virtual Consultation",
    role: "Father",
    noOfChildren: "1",
    nameOfChild: "Shayne Ajasco",
    dob: "22-01-2021",
    weight: "10kg",
    allergies: "peanut",
    specialNeeds: "",
    medCondition: "",
    sex: "Male",
    age: "2 year",
    complaint: "Running Temperature",
    prescription: "Chloraphenicol, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "05-02-2021",
    time: "3:00 PM",
    status: "Pending",
  },
  {
    id: 3,
    serialno: "0581",
    caregiver: "Vince Calistus",
    email: "email@hotmail.com",
    phone: "+2347034536782",
    address: "15 Oladipo Diya Avenue V.I, Lagos",
    location: "Health Center",
    doctor: "Obinna Okereke",
    requestType: "Vaccination",
    role: "Guardian",
    noOfChildren: "3",
    nameOfChild: "Vinnie Santino",
    dob: "22-01-2021",
    weight: "10kg",
    allergies: "peanut",
    specialNeeds: "",
    medCondition: "",
    sex: "Male",
    age: "6 Months",
    complaint: "Dysentry",
    prescription: "Vitamin B Complex, Multivitamin syrup",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "24-03-2021",
    time: "9:00 AM",
    status: "Completed",
  },
  {
    id: 4,
    serialno: "0941",
    caregiver: "Adekunle Taribo",
    email: "guruemail@hotmail.com",
    phone: "+2347034536782",
    address: "15 Oladipo Diya Avenue V.I, Lagos",
    location: "Home",
    doctor: "Johnny Maguire",
    requestType: "Virtual Consultation",
    role: "Mother",
    noOfChildren: "2",
    sex: "Female",
    age: "1 year",
    nameOfChild: "Adekunle Simi",
    dob: "22-01-2021",
    weight: "10kg",
    allergies: "peanut",
    specialNeeds: "",
    medCondition: "",
    complaint: "Cold",
    prescription: "Vitamin B Complex, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "03-05-2021",
    time: "12:00 AM",
    status: "Absent",
  },
  {
    id: 5,
    serialno: "0781",
    caregiver: "Lucy Ekanem",
    email: "email@hotmail.com",
    phone: "+2347034536782",
    address: "15 Oladipo Diya Avenue V.I, Lagos",
    location: "Home",
    doctor: "Peter Drury",
    requestType: "Virtual Consultation",
    role: "Mother",
    noOfChildren: "1",
    nameOfChild: "Iniobong Abang",
    dob: "22-01-2021",
    weight: "10kg",
    allergies: "peanut",
    specialNeeds: "",
    medCondition: "",
    sex: "Female",
    age: "1 year",
    complaint: "Fever",
    prescription: "Paracetamol, Folic Acid and Vitamin C",
    doctorsAdvice:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dateOfReg: "25-04-2021",
    time: "11:00 AM",
    status: "Accepted",
  },
];