export const childrenData = [
  {
    id: 1,
    nameOfChild: "Nneka Ossai",
    sex: "Male",
    age: "2 months",
    dob: "24-01-2021",
    weight: "28kg",
    medicalCondition: "Asthma",
    allegies: "Peanuts",
    dateOfReg: "24-05-2021",
    caregiver: "Nneka Chigbogwu",
    city: "Port Harcourt",
    state: "Rivers State, NG",
  },
  {
    id: 2,
    nameOfChild: "Maryam Aliyu",
    sex: "Female",
    age: "2 years",
    dob: "24-01-2021",
    weight: "24kg",
    medicalCondition: "Dysentry",
    allegies: "dust",
    dateOfReg: "24-05-2021",
    caregiver: "Nneka Chigbogwu",
    city: "Ketu",
    state: "Lagos, NG",
  },
  {
    id: 3,
    nameOfChild: "Vince Calistus",
    sex: "Male",
    age: "2 years",
    dob: "24-01-2021",
    weight: "30kg",
    medicalCondition: "Dysentry",
    allegies: "dust",
    dateOfReg: "24-05-2021",
    caregiver: "Ahmadu Flavour",
    city: "Lekki",
    state: "Lagos, NG",
  },
  {
    id: 4,
    nameOfChild: "Adekunle Taribo",
    sex: "Male",
    age: "3 years",
    dob: "24-01-2021",
    weight: "24kg",
    medicalCondition: "Dysentry",
    allegies: "dust",
    dateOfReg: "24-05-2021",
    caregiver: "Nneka Chigbogwu",
    city: "Surulere",
    state: "Lagos, NG",
  },
  {
    id: 5,
    nameOfChild: "Lucy Ekanem",
    sex: "Female",
    age: "1 year",
    dob: "24-01-2021",
    weight: "24kg",
    medicalCondition: "Dysentry",
    allegies: "dust, Peanuts",
    dateOfReg: "24-05-2021",
    caregiver: "Lucy Ekanem",
    city: "Port Harcourt",
    state: "Rivers State, NG",
  },
];